<?php
session_start();
require_once('../model/userModel.php');
require_once('../model/tournamentModel.php');

// 1. Security check: Only admin can access
if (!isset($_COOKIE['status']) || $_SESSION['role'] !== 'Admin') {
    header('location: home.php?error=unauthorized');
    exit();
}

// 2. Data fetching
$users = getAllUsers();
$tournaments = getAllTournaments();
$activeTournaments = getActiveTournamentCount();
$date = date('d F, Y - h:i A');
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>System Report</title>
    <link rel="stylesheet" href="../asset/css/style.css">
    <style>
        /* CSS to hide buttons and links when printing */
        @media print {
            .no-print {
                display: none;
            }

            fieldset {
                border: none;
                margin: 0;
                width: 100%;
            }

            body {
                background-color: white;
            }
        }
    </style>
</head>

<body>
    <fieldset style="width: 850px; margin: 30px auto;">
        <legend>System Report Generation</legend>

        <div class="no-print" style="text-align: center; margin-bottom: 20px;">
            <a href="home.php">Back to Dashboard</a> |
            <button onclick="window.print()"
                style="cursor: pointer; padding: 5px 10px; background: #0066cc; color: white; border: none; border-radius: 3px;">🖨️
                Print / Save PDF</button>
        </div>
        <hr class="no-print">

        <div style="text-align: center;">
            <h2>Tournament Management System</h2>
            <h3>Official System Report</h3>
            <p><strong>Generated By:</strong> <?php echo $_SESSION['username']; ?> | <strong>Date:</strong>
                <?php echo $date; ?></p>
        </div>

        <br>

        <h3>1. System Summary</h3>
        <table border="1" cellspacing="0" cellpadding="8" style="width: 100%; text-align: left;">
            <tr>
                <th style="background-color: #eee;">Metric</th>
                <th style="background-color: #eee;">Count</th>
            </tr>
            <tr>
                <td>Total Registered Users</td>
                <td><?php echo count($users); ?></td>
            </tr>
            <tr>
                <td>Total Tournaments Hosted</td>
                <td><?php echo count($tournaments); ?></td>
            </tr>
            <tr>
                <td>Currently Active Tournaments</td>
                <td><?php echo $activeTournaments; ?></td>
            </tr>
        </table>

        <br>

        <h3>2. Tournament Status Report</h3>
        <table border="1" cellspacing="0" cellpadding="8" style="width: 100%; text-align: center;">
            <tr style="background-color: #eee;">
                <th>ID</th>
                <th>Title</th>
                <th>Category</th>
                <th>Status</th>
                <th>Created By</th>
            </tr>
            <?php foreach ($tournaments as $t): ?>
                <tr>
                    <td><?php echo $t['id']; ?></td>
                    <td><?php echo $t['title']; ?></td>
                    <td><?php echo $t['category']; ?></td>
                    <td>
                        <?php
                        if ($t['status'] == 'Upcoming')
                            echo '<span style="color: blue;">Upcoming</span>';
                        elseif ($t['status'] == 'Ongoing')
                            echo '<span style="color: green;">Ongoing</span>';
                        else
                            echo '<span style="color: red;">Completed</span>';
                        ?>
                    </td>
                    <td><?php echo $t['created_by']; ?></td>
                </tr>
            <?php endforeach; ?>
        </table>

        <br>
        <div style="text-align: center; font-size: 12px; color: gray;">
            <p>--- End of Report ---</p>
        </div>

    </fieldset>
</body>

</html>