<?php
session_start();
require_once('../model/userModel.php');
require_once('../model/tournamentModel.php');
if (!isset($_COOKIE['status']) || $_SESSION['role'] !== 'Admin') { header('location: home.php?error=unauthorized'); exit(); }
$users = getAllUsers();
$tournaments = getAllTournaments();
$activeTournaments = getActiveTournamentCount();
$date = date('d F, Y - h:i A');
?>
<!DOCTYPE html>
<html>
<head><title>System Report</title><link rel="stylesheet" href="../asset/css/style.css">
    <style> @media print { .no-print { display: none; } fieldset { border: none; margin: 0; width: 100%; } } </style>
</head>
<body>
    <fieldset style="width: 850px; margin: 30px auto;">
        <legend>System Report Generation</legend>
        <div class="no-print" style="text-align: center; margin-bottom: 20px;"><a href="home.php">Back to Dashboard</a> | <button onclick="window.print()">Print / Save PDF</button></div>
        <div style="text-align: center;"><h2>Tournament Management System</h2><p><strong>Generated By:</strong> <?php echo $_SESSION['username']; ?> | <strong>Date:</strong> <?php echo $date; ?></p></div>
        <h3>1. System Summary</h3>
        <table border="1" cellspacing="0" cellpadding="8" style="width: 100%;">
            <tr><th>Metric</th><th>Count</th></tr>
            <tr><td>Total Users</td><td><?php echo count($users); ?></td></tr>
            <tr><td>Total Tournaments</td><td><?php echo count($tournaments); ?></td></tr>
        </table>
        <h3>2. Tournament Status</h3>
        <table border="1" cellspacing="0" cellpadding="8" style="width: 100%; text-align: center;">
            <tr><th>ID</th><th>Title</th><th>Category</th><th>Status</th></tr>
            <?php foreach ($tournaments as $t): ?>
                <tr><td><?php echo $t['id']; ?></td><td><?php echo $t['title']; ?></td><td><?php echo $t['category']; ?></td><td><?php echo $t['status']; ?></td></tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</body>
</html>
